# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import os
import glob
from snakemake.utils import min_version

min_version("9.1.6")


configfile: "config/config.yaml"


# list all subfolders in input_dir
sample_dirs = [
    sample
    for sample in os.listdir(config["input_dir"])
    if os.path.isdir(os.path.join(config["input_dir"], sample))
    and "unclassified" not in sample.lower()
]


# include: "rules/01-cat_fastq.smk"
# include: "rules/02-qfilter.smk"
# concat totalreads files here
# include: "rules/03-rename_samples.smk"
include: "rules/01-sample_prep.smk"
include: "rules/02-primertrim.smk"
include: "rules/03-subsample.smk"

# include: "rules/02-denoise.smk"
# include: "rules/03-rename_known_zotus.smk"
# include: "rules/04-sintax.smk"
# include: "rules/05-abund_table.smk"

rule all:
    input:
        expand(
            [
                os.path.join(config["tmp_dir"], "totalreads", "{sample}_totalreads.csv"),
                os.path.join(config["tmp_dir"], "totalreads_trimmed", "{sample}_totaltrimmedreads.csv"),
                os.path.join(config["output_dir"], "subsample", "subsample_summary.tsv"),
            ],
            sample=sample_dirs,
        )