# This file is for various variables used throughout the workflow.
# See a description of each setting in the README.md file.
input_dir: ".test/nanopore_run_xyz123/fastq_pass"
output_dir: "output"
tmp_dir: "tmp"
log_dir: "logs"
# to skip filtering altogether set to "--min_length 1"
filtlong_args: "--min_length 1"
subsample_sizes: [10000, 20000, 50000, 100000, 200000]
max_threads: 32
sample_sep: "_"
primers: "AGRGTTYGATYMTGGCTCAG...GTTTGGCACCTCGATGTCG"

